### ISSUE TITLE
Unable to build Docker images

### ISSUE THREAD

**Issue by Blason** [SecureAuthCorp/HoneySAP#1]
Hi Folks,

I am pretty novice to docker and wondering if you guys can help me creating a docker image of honeysap? I am building a docker image from Dockerfile and its failing at below stage; somehow this is not able to copy the file however I see the file is present but not sure why the file is not being copied?

Running hooks in /etc/ca-certificates/update.d...
done.
Removing intermediate container 732fd1affe22
 ---> 173bb8764c78
Step 4/9 : COPY . /opt/honeysap
 ---> 9a9b72db1a6c
Step 5/9 : WORKDIR /opt/honeysap
 ---> Running in 9017f5898dfb
Removing intermediate container 9017f5898dfb
 ---> e3c6d22a7dda
Step 6/9 : RUN cd /opt/honeysap &&     python setup.py install &&     rm -rf /tmp/* /var/tmp/*
 ---> Running in 6a7cd3e86d91
python: can't open file 'setup.py': [Errno 2] No such file or directory
The command '/bin/sh -c cd /opt/honeysap &&     python setup.py install &&     rm -rf /tmp/* /var/tmp/*' returned a non-zero code: 2

**Comment by martingalloar** [comment]
Hey @Blason!

As the `Dockerfile` is in the `deployment` folder, I think it's just a matter of pointing to the right directory when building the image. If you checked out the repository and are on the root folder, you should build the image with the following command:

```
docker build -f deployment/Dockerfile .
```

Can you check that?

**Comment by Blason** [comment]
Thanks and I forgot to update that I resolved the issue. However there is not documentation for running the docker or I want to run the docker using docker-compose.

Would you be kind enough to post the document for running the docker?

**Comment by martingalloar** [comment]
That's a good idea and I'd love to be able to do it, but currently can't assign time for this. Anyway, contributions are welcomed and feel free to issue PR for this, even if it's partial work.

**Comment by Blason** [comment]
I am on it and need guidance from creator. How do I run the Docker version any hints are realyl appreciated.
