### ISSUE TITLE
Need pre-configured HoneySAP conf file as a reference

### ISSUE THREAD

**Issue by Blason** [SecureAuthCorp/HoneySAP#2]
Hey there,

Is there any way or would really appreciate if you can provide me the preconfigured or template HoneySAP config file for reference pls? I am going through the docs but certain things are still not clear hence wanted to understand by referring to template or config file.

TIA 
Blason R

**Comment by martingalloar** [comment]
Hey Blason! The [profiles](https://github.com/SecureAuthCorp/HoneySAP/tree/master/profiles) folder provides some examples that you might use as starting points:
- [external.yml](https://github.com/SecureAuthCorp/HoneySAP/blob/master/profiles/external.yml): an external looking instance with a SAPRouter exposed with a [minimal route](https://github.com/SecureAuthCorp/HoneySAP/blob/master/profiles/external_route_table.yml) to an internal Dispatcher service.
- [internal.yml](https://github.com/SecureAuthCorp/HoneySAP/blob/master/profiles/internal.yml): an internal looking instance with a dispatcher service exposed.

Feel free to send pull request with additional configuration profiles that might work for you!

Take into account that the project as a whole was an experimental initiative and it haven't been touched too much recently, you might need to tweak portions of the code as well.

**Comment by Blason** [comment]
Well I am building Docker image and working to integrate this honeypot with cowrie. Also wondering how and where are the logs generated? In what format. Since I am using logstash let me see if I can parse those and forward into my ELK stack.

**Comment by martingalloar** [comment]
In the initial design, logs are generated using the concept of [events](https://github.com/SecureAuthCorp/HoneySAP/blob/master/honeysap/core/event.py) that each service generates, and are consumed and processed by a [feed manager](https://github.com/SecureAuthCorp/HoneySAP/blob/master/honeysap/core/feed.py). There're a couple of basic feeds already available [here](https://github.com/SecureAuthCorp/HoneySAP/tree/master/honeysap/feeds), you might want to add a new feed for pushing events to logstash.

**Comment by Blason** [comment]
Thanks man!! I am facing lot of difficulties setting up this as a docker and you being an author might need your extensive help setting up as a docker-compose file. Hope you don't mind that. My ultimate goal is to setup docker image and take logs and forward it my ELK.
