### ISSUE TITLE
Want to understand Logging & diverting to ELK

### ISSUE THREAD

**Issue by Blason** [SecureAuthCorp/HoneySAP#3]
Hi Moderator,

I need to understand the logging of HoneySAP and then divert those logs to ELK. I see there is a ansible file but not sure where are the logs being stored? Or if those are in Json format so that I can directly ingest in my ELK stack?

**Comment by martingalloar** [comment]
Hey! I don't think the ansible files are of any help. As suggested in #2, you might want to take a look at the current feeds modules and see if any of them can help you, or create a new one. The [logfeed.py](https://github.com/SecureAuthCorp/HoneySAP/blob/master/honeysap/feeds/logfeed.py) can be used as a base but doesn't output in JSon format.

**Comment by Blason** [comment]
hey, let me have a look at logfeed.py. I guess if not in json I can use logstash for parsing and then divert those logs to ELK.
