### ISSUE TITLE
Unable to run Dockerized version

### ISSUE THREAD

**Issue by Blason** [SecureAuthCorp/HoneySAP#6]
Hi,

Unable to run the dockerized version of the HoneySAP however when I am running with installation and pointing to the same file it worked perfectly.
#### 
WARNING: Failed to execute tcpdump. Check it is installed and in the PATH
Traceback (most recent call last):
  File "/usr/local/bin/honeysap", line 4, in <module>
    __import__('pkg_resources').run_script('honeysap==0.1.2.dev0', 'honeysap')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/honeysap-0.1.2.dev0-py2.7.egg/EGG-INFO/scripts/honeysap", line 30, in <module>
    honeysap.main()
  File "/usr/local/lib/python2.7/dist-packages/honeysap-0.1.2.dev0-py2.7.egg/honeysap/core/honeysap.py", line 42, in main
    self.get_configuration()
  File "/usr/local/lib/python2.7/dist-packages/honeysap-0.1.2.dev0-py2.7.egg/honeysap/core/honeysap.py", line 70, in get_configuration
    (self.config, __) = parser.parse_args(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/honeysap-0.1.2.dev0-py2.7.egg/honeysap/core/config.py", line 259, in parse_args
    configuration.update(configuration.config_file, from_file=True)
  File "/usr/local/lib/python2.7/dist-packages/honeysap-0.1.2.dev0-py2.7.egg/honeysap/core/config.py", line 193, in update
    raise ConfigurationParserNotFound("None of the available configuration "
honeysap.core.config.ConfigurationParserNotFound: None of the available configuration parsers is able to parse the configuration file
###########
While installation works perfectly fine

root@saphp:/opt/HoneySAP# honeysap -c profiles/honeysap.yml
honeysap.HoneySAP - 2020-03-13 08:59:07,936 - INFO     - Using config: {'_config_files': ['profiles/external_route_table.yml',
                   'profiles/honeysap.yml'],
 'colored_console': True,
 'config_file': 'profiles/honeysap.yml',
 'feeds': [{'enabled': True,
            'feed': 'LogFeed',
            'log_filename': 'honeysap-external.log'},
           {'enabled': True, 'feed': 'ConsoleFeed'},
           {'channels': ['honeysap.events'],
            'enabled': False,
            'feed': 'HPFeed',
            'feed_host': '10.250.250.20',
            'feed_ident': 'honeysap',
            'feed_port': 20000,
            'feed_secret': 'password'}],
 'listener_address': '0.0.0.0',
 'release': '720',
 'reload': False,
 'services': [{'alias': 'ExternalSAPRouter',
               'enabled': True,
               'external_admin': False,
               'hostname': 'saprouter',
               'info_password': 'Passw0rd',

**Comment by martingalloar** [comment]
I'm unable to test the docker deployment and it was actually a contribution from someone else, but I suspect you're trying to use a YAML configuration file and the `PyYAML` library is not installed inside the docker environment. Can you validate that?

**Comment by Blason** [comment]
Hmm..let me have a look and get back to you..by the way how configuration changes needed to start logging into different file like /var/log/honeysap_external.log

**Comment by Blason** [comment]
Plus does not look like that is the issue - since I see the PyYAML is already installed

Installed /usr/local/lib/python2.7/dist-packages/MarkupSafe-1.1.1-py2.7-linux-x86_64.egg
Finished processing dependencies for honeysap==0.1.2.dev0
Removing intermediate container 5bed475afe1a
 ---> 9d8a76ba5bed
Step 7/10 : RUN pip install -r requirements.txt
 ---> Running in 3a3ac9a2ed38
Requirement already satisfied: pysap==0.1.8 in /usr/local/lib/python2.7/dist-packages/pysap-0.1.8-py2.7-linux-x86_64.egg (from -r requirements.txt (line 1))
Requirement already satisfied: flask==1.0 in /usr/local/lib/python2.7/dist-packages/Flask-1.0-py2.7.egg (from -r requirements.txt (line 2))
Requirement already satisfied: gevent==1.0.2 in /usr/local/lib/python2.7/dist-packages/gevent-1.0.2-py2.7-linux-x86_64.egg (from -r requirements.txt (line 3))
Requirement already satisfied: SQLAlchemy==1.3.0 in /usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.3.0-py2.7-linux-x86_64.egg (from -r requirements.txt (line 4))
**Requirement already satisfied: PyYAML==4.2b4 in /usr/local/lib/python2.7/dist-packages/PyYAML-4.2b4-py2.7-linux-x86_64.egg (from -r requirements.txt (line 5))**
Requirement already satisfied: colorlog==3.1.4 in /usr/local/lib/python2.7/dist-packages/colorlog-3.1.4-py2.7.egg (from -r requirements.txt (line 6))
Requirement already satisfied: jsoncomment==0.3.0 in /usr/local/lib/python2.7/dist-packages/jsoncomment-0.3.0-py2.7.egg (from -r requirements.txt (line 7))
Requirement already satisfied: Jinja2<3.0.0 in /usr/local/lib/python2.7/dist-packages/Jinja2-2.11.1-py2.7.egg (from -r requirements.txt (line 8))
Requirement already satisfied: epydoc==3.0.1 in /usr/local/lib/python2.7/dist-packages/epydoc-3.0.1-py2.7.egg (from pysap==0.1.8->-r requirements.txt (line 1))
Requirement already satisfied: scapy==2.3.1 in /usr/local/lib/python2.7/dist-packages/scapy-2.3.1-py2.7.egg (from pysap==0.1.8->-r requirements.txt (line 1))
Requirement already satisfied: Werkzeug>=0.14 in /usr/local/lib/python2.7/dist-packages/Werkzeug-1.0.0-py2.7.egg (from flask==1.0->-r requirements.txt (line 2))
Requirement already satisfied: click>=5.1 in /usr/local/lib/python2.7/dist-packages/click-7.1.1-py2.7.egg (from flask==1.0->-r requirements.txt (line 2))
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python2.7/dist-packages/itsdangerous-1.1.0-py2.7.egg (from flask==1.0->-r requirements.txt (line 2))
Requirement already satisfied: greenlet>=0.4.7 in /usr/local/lib/python2.7/dist-packages/greenlet-0.4.15-py2.7-linux-x86_64.egg (from gevent==1.0.2->-r requirements.txt (line 3))

and I am still getting the same error
WARNING: Failed to execute tcpdump. Check it is installed and in the PATH
Traceback (most recent call last):
  File "/usr/local/bin/honeysap", line 4, in <module>
    __import__('pkg_resources').run_script('honeysap==0.1.2.dev0', 'honeysap')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/honeysap-0.1.2.dev0-py2.7.egg/EGG-INFO/scripts/honeysap", line 30, in <module>
    honeysap.main()
  File "/usr/local/lib/python2.7/dist-packages/honeysap-0.1.2.dev0-py2.7.egg/honeysap/core/honeysap.py", line 42, in main
    self.get_configuration()
  File "/usr/local/lib/python2.7/dist-packages/honeysap-0.1.2.dev0-py2.7.egg/honeysap/core/honeysap.py", line 70, in get_configuration
    (self.config, __) = parser.parse_args(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/honeysap-0.1.2.dev0-py2.7.egg/honeysap/core/config.py", line 259, in parse_args
    configuration.update(configuration.config_file, from_file=True)
  File "/usr/local/lib/python2.7/dist-packages/honeysap-0.1.2.dev0-py2.7.egg/honeysap/core/config.py", line 193, in update
    raise ConfigurationParserNotFound("None of the available configuration "
honeysap.core.config.ConfigurationParserNotFound: None of the available configuration parsers is able to parse the configuration file

**Comment by Blason** [comment]
Seems tohave resolved the issue with Slight modification in Dockerfile

more /opt/HoneySAP/deployment/Dockerfile
# HoneySAP Dockerfile for running HoneySAP

FROM ubuntu:18.04

MAINTAINER mgallo@secureauth.com

# Install system packages
RUN apt-get update && apt-get install -y \
        git \
        python-pip \
        python-dev \
        build-essential python-yaml && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY . /opt/honeysap
WORKDIR /opt/honeysap

# Clone git repo and install HoneySAP
RUN cd /opt/honeysap && \
    python setup.py install && \
    rm -rf /tmp/* /var/tmp/*

# Install extra python packages
RUN pip install -r requirements.txt
RUN pip install -r requirements-optional.txt

EXPOSE 3299 8001

**CMD ["/usr/local/bin/honeysap", "-c", "/opt/honeysap/profiles/external.yml"]**

**Comment by martingalloar** [comment]
Thanks, that's great! I'll keep this in mind and try to include a couple of fix (adding python-yaml and using a mount point for the configuration file instead of copying it).
