### ISSUE TITLE
Python 3.x support

### ISSUE THREAD

**Issue by t3chn0m4g3** [SecureAuthCorp/HoneySAP#8]
With Python 2.x being deprecated for a while now and most of the distros closing support for Python 2.x are you planning to support Python3.x in the near future?

**Comment by t3chn0m4g3** [comment]
Obviously not :bowtie:

**Comment by martingalloar** [comment]
Sorry the delay! Supporting 3.x is a long-standing issue, but the juicy parts of HoneSAP rely on pysap which also need to complete support for it. This effort has been in progress for quite some time in https://github.com/SecureAuthCorp/pysap/projects/1

**Comment by t3chn0m4g3** [comment]
Thank you for the feedback! Very much appreciated and also you guys are working on a Py3 version!

**Comment by Skr1ptKid-0x** [comment]
indeed.
